config/routes.rb
Rails.application.routes.draw do
  resources :torpedos
  resources :fistros
  root :to => 'fistros#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fistro.rb
class Fistro < ApplicationRecord
end

app/models/torpedo.rb
class Torpedo < ApplicationRecord
  mount_uploader :image, ImageUploader
  after_save :enqueue_image

  def image_name
    File.basename(image.path || image.filename) if image
  end

  def enqueue_image
    ImageWorker.perform_async(id, key) if key.present?
  end

  class ImageWorker
    include Sidekiq::Worker

    def perform(id,key)
      torpedo = Torpedo.find(id)
      torpedo.key = key
      torpedo.remote_image_url = torpedo.image.direct_fog_url(with_path: true)
      torpedo.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fistros_controller.rb
class FistrosController < ApplicationController

  def show
    @fistro = Fistro.find(params[:id])
  end

  def index
    @fistro = Fistro.new
    @fistros ||= fistro_search
  end

  def create
    @fistro = Fistro.new(fistro_params)
    if @fistro.save
      redirect_to @fistro
    else
      render 'new'
    end
  end

  def edit
    @fistro = Fistro.find(params[:id])
  end

  private

    def fistro_params
      params.require(:fistro).permit(:select1, :select2,:text2)
    end

    def fistro_search
      fistro = Fistro.all
      fistro = Fistro.where(:select1 => params[:select1]) if params[:select1].present?
      fistro = Fistro.where(:select2 => params[:select2]) if params[:select2].present?
      fistro = Fistro.where(:text2 => params[:text_from]..params[:text_to]) if params[:text_to].present?
      fistro
    end

  end

app/controllers/torpedos_controller.rb
class TorpedosController < ApplicationController
  before_action :set_torpedo, only: [:show, :edit, :update, :destroy]

  # GET /torpedos
  # GET /torpedos.json
  def index
    @torpedos = Torpedo.all
    @benemeritar = Torpedo.new.image
    @benemeritar.success_action_redirect = new_torpedo_url
  end

  # GET /torpedos/1
  # GET /torpedos/1.json
  def show
  end

  # GET /torpedos/new
  def new
    @torpedo = Torpedo.new(key: params[:key])
  end

  # GET /torpedos/1/edit
  def edit
  end

  # POST /torpedos
  # POST /torpedos.json
  def create
    @torpedo = Torpedo.new(torpedo_params)

    respond_to do |format|
      if @torpedo.save
        format.html { redirect_to @torpedo, notice: 'Torpedo was successfully created.' }
        format.json { render :show, status: :created, location: @torpedo }
      else
        format.html { render :new }
        format.json { render json: @torpedo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /torpedos/1
  # PATCH/PUT /torpedos/1.json
  def update
    respond_to do |format|
      if @torpedo.update(torpedo_params)
        format.html { redirect_to @torpedo, notice: 'Torpedo was successfully updated.' }
        format.json { render :show, status: :ok, location: @torpedo }
      else
        format.html { render :edit }
        format.json { render json: @torpedo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /torpedos/1
  # DELETE /torpedos/1.json
  def destroy
    @torpedo.destroy
    respond_to do |format|
      format.html { redirect_to torpedos_url, notice: 'Torpedo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_torpedo
      @torpedo = Torpedo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def torpedo_params
      params.require(:torpedo).permit(:name, :image, :remote_image_url, :key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fistros_helper.rb
module FistrosHelper
  def select_fistro_1
    fistro = Fistro.select(:select1).where.not(:select1 => nil)
    fistro.map.each do |camarerorl|
      camarerorl.select1.to_s
    end
  end
  def select_fistro_2
    fistro = Fistro.select(:select2).where.not(:select2 => nil)
    fistro.map.each do |camarerorl|
      camarerorl.select2.to_s
    end
  end
end

app/helpers/torpedos_helper.rb
module TorpedosHelper
end

app/views/fistros/_fistros.html.erb
<div class="container">
    <%= form_tag @fistro, method: 'get' do %>
        <div class="row">
            <div class="left">
                <%= select_tag :select1, options_for_select(select_fistro_1), :include_blank => true%>
                <%= select_tag :select2, options_for_select(select_fistro_2), :include_blank => true%>
            </div>
            <div class="middle">
                <%= text_field_tag :text_from, nil, :class => "text" %>
                <%= text_field_tag :text_to, nil, :class => "text" %>
            </div>
            <div class="right">
            <%= submit_tag "AL ATAQUER", name: nil %>
            </div>
        </div>
        <%= render partial: 'pecadorl' %>
    <% end %>
</div>

app/views/fistros/_pecadorl.html.erb
<ul>
  <% @fistros.each do |f| %>
    <li>Fistro #<%= f.id %></li>
    <li><%= f.select1 %></li>
    <li><%= f.select2 %></li>
    <li><%= f.text2 %></li>
    <br>
  <% end %>
</ul>
<%= link_to "AGRAMENAUER!", fistros_path %>

app/views/fistros/index.html.erb
<h1>Fistros#index</h1>
<p>Find me in app/views/fistros/index.html.erb</p>
<%= render partial: 'fistros' %>

app/views/fistros/show.html.erb
 <div class="container">
  <div class="row left">
    <%= @fistro.id %>
    <%= @fistro.select1 %>
  </div>
  <div class="row right">
    <%= @fistro.select2 %>
    <%= @fistro.text2 %>
  </div>
  <div class="row middle">
    <%= link_to "AGRAMENAUER!", fistros_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/torpedos/_form.html.erb
<%= simple_form_for(@torpedo) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :key %>
  <div class="form-inputs">
    <%= f.text_field :name %>
    <%= @torpedo.image_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/torpedos/edit.html.erb
<h1>Editing Torpedo</h1>

<%= render 'form', torpedo: @torpedo %>

<%= link_to 'Show', @torpedo %> |
<%= link_to 'Back', torpedos_path %>

app/views/torpedos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Torpedos</h1>

<%= direct_upload_form_for @benemeritar do |comisaridar| %>
  <p><%= comisaridar.file_field :image %></p>
  <p><%= comisaridar.submit "No te digo trigo" %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Img</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @torpedos.each do |torpedo| %>
      <tr>
        <td><%= torpedo.name %></td>
        <td><%= image_tag(torpedo.image)%></td>
        <td><%= link_to 'Show', torpedo %></td>
        <td><%= link_to 'Edit', edit_torpedo_path(torpedo) %></td>
        <td><%= link_to 'Destroy', torpedo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/torpedos/new.html.erb
<h1>New Torpedo</h1>

<%= render 'form', torpedo: @torpedo %>

<%= link_to 'Back', torpedos_path %>

app/views/torpedos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @torpedo.name %>
</p>

<p>
  <strong>Img:</strong>
  <%= image_tag(@torpedo.image).to_s %> 
</p>

<%= link_to 'Edit', edit_torpedo_path(@torpedo) %> |
<%= link_to 'Back', torpedos_path %>